///REGISTER USER
export const SIGNUP_NEW_USER = "SIGNUP_NEW_USER";

// AUTH Constants
export const FETCH_TOKEN = "FETCH_TOKEN";
export const FETCH_TOKEN_FAILED = "FETCH_TOKEN_FAILED";
export const TOKEN_REMOVE = "TOKEN_REMOVE";

//USERS CONSTANTS
export const TOGGLE_ACTIVITY = "TOGGLE_ACTIVITY";
export const GET_USERS = "GET_USERS";
export const GET_USERSDATES = "GET_USERSDATES";
export const GET_USER = "GET_USER"
export const GET_USERLINKS = "GET_USERLINKS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_LINK = "DELETE_LINK";

//LINKTYPES CONSTS
export const GET_LINKTYPES = "GET_LINKTYPES";
export const ADD_LINKTYPE = "ADD_LINKTYPE";
export const EDIT_LINKTYPE = "EDIT_LINKTYPE";
export const EDIT_LINKICON = "EDIT_LINKICON";

//ADMINS CONSTANTS
export const GET_ADMINS = "GET_ADMINS";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const CHANGE_ROLE = "CHANGE_ROLE";

// App Notification
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_NOTIFICATION_OFF = "TOGGLE_NOTIFICATION_OFF";
